spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jap:
    show-sql: true
#全局配置对象为空就不返回
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx7985a08a1c822f64
  mpAppSecret: dfd295f26f4a4a6ce0c0d04dea5d3124


